name: contacts_service_example
description: Demonstrates how to use the contacts_service plugin.

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  contacts_service_plus:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
